"""add owner_id col in posts table

Revision ID: c3f7bf15c1a1
Revises: 5f51198c1375
Create Date: 2026-05-30 01:00:29.601814

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c3f7bf15c1a1"
down_revision: Union[str, Sequence[str], None] = "5f51198c1375"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("owner_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        None, "posts", "users", ["owner_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "posts", type_="foreignkey")  # type: ignore
    op.drop_column("posts", "owner_id")
    # ### end Alembic commands ###
