name: Run tests

on: 
  push:
  pull_request:

jobs:                                      # all job runs parallely and independently which tells cause of failure seperately.
  lint:                                    
    runs-on: ubuntu-latest

    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.10"
          cache: "pip"
          cache-dependency-path: requirements.txt
      - run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run Ruff Linter
        run: ruff check .                    # check unused import/variables. 

      - name: Run Ruff Format check
        run: ruff format --check             # --check: ruff won't automatically fix the format. 

  security:
    runs-on: ubuntu-latest

    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.10"
          cache: "pip"
          cache-dependency-path: requirements.txt
      - run: |
          python -m pip install --upgrade pip
          pip install requirements.txt
          pip install pip-audit
        
      - name: Audit dependencies for known vulnerabilities
        run: pip-audit

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: fastapi_test
        options: >-                        # Health check confirms our db is started and ready for connection.
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    
    env:
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: fastapi_test
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python 
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.10"
          cache: "pip"                                  # Collects cached dependencies instead of fresh install.
          cache-dependency-path: requirements.txt

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python -m pytest -v -x --tb=short

      - name: Setup Docker Buildx                      # Modern buildkit from dockers in-built in GHA. 
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: social-media-api:latest
          cache-from: type=gha
          cache-to: type=gha, mode=max